<?php
/**
 * @var $block \Ebizmarts\Mailchimp\Block\Mailchimpjs
 */
$url = $block->getJsUrl();
$render = $block->getRender();
//echo $render->renderTag('script',['type'=>'text/javascript','src'=>$escaper->escapeUrl($url),'defer'=>'defer'],"\n",true);
echo $render->renderTag('script',['type'=>'text/plain','data-suppressedsrc'=>$escaper->escapeUrl($url),'defer'=>'defer','data-iub-purposes'=>'2'],"\n",true);
?>
